### ISSUE TITLE
how to disable rollback button?

### ISSUE THREAD

**Issue by jcsky** [rikkipitt/rails_admin_history_rollback#18]
just as title
sometimes, I don't want admin user do rollback action

**Comment by rikkipitt** [comment]
Hi @jcsky, have you seen CanCan before? It's an authorisation library for Ruby on Rails which restricts what resources a given user is allowed to access. The rails_admin_history_rollback gem integrates with CanCan nicely.

The latest version is actually called CanCanCan (because CanCan went unmaintained).

https://github.com/CanCanCommunity/cancancan

Hope this helps!

Rikki
